/*
  VALLEY BASEBALL STRENGTH AND POWER PROGRAM
  ------------------------------------------
  This file is the program. Edit it on GitHub to change what players see.
  After saving, change VERSION in sw.js (for example traininglog-v3) so phones pick up the change.

  Each exercise line reads:  ['exercise id', sets, 'target', 'coaching note', rest in seconds]
    target examples:  '8'  '6-10'  '10 ea' (each side)  '30s' (seconds)  '50 ft'  '40 yd'
  Keep the quotes and commas exactly as they are. Exercise ids must match the library at the bottom.
*/
window.PROGRAM = {
  name: 'Valley Baseball Strength and Power',

  // Team start date (a Monday), written 'YYYY-MM-DD'. Leave as '' to let each player's
  // schedule begin on the day of their first session.
  startDate: '',

  // Coach approval code check. Ask for help to change the code.
  coachKey: '0604ee15',

  days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday'],
  dayTitles: ['Lower Body Power and Core', 'Upper Body Strength', 'Rotational Power and Core', 'Full Body Power and Conditioning'],

  phases: [
    { name: 'Foundation', weeks: 2, rpe: '6 to 7', rpeText: 'Finish your last set with 3 to 4 good reps left.',
      focus: 'Perfect form, build the habit, build work capacity.' },
    { name: 'Strength', weeks: 2, rpe: '7 to 8', rpeText: 'Finish your last set with 2 to 3 good reps left.',
      focus: 'Add weight steadily and build your strength base.' },
    { name: 'Power', weeks: 2, rpe: '8 on heavy lifts', rpeText: 'Heavy lifts: about 2 reps left. Jumps and throws: fast and crisp, never slow.',
      focus: 'Turn strength into speed. Move every rep fast.' },
    { name: 'Peak', weeks: 3, rpe: '8 to 9', rpeText: 'Leave 1 to 2 reps in the tank. Never grind out a rep.',
      focus: 'Heavier with fewer reps, maximum speed. Carry it into the season.' }
  ],

  // Speed work opens Monday and Wednesday sessions. One list per phase: [Mon, Tue, Wed, Thu].
  speed: [
    [ [['s10', 5, '10 yd', 'Two-point start. Build to full speed by week 2. Walk back to recover.', 60]], [],
      [['proag', 4, '', 'Learn the footwork first. Touch the line with your hand at each turn.', 60]], [] ],
    [ [['s10', 4, '10 yd', 'Full speed. Explode out of your stance.', 60], ['s30', 3, '30 yd', 'Stay low for the first 10 yards, then run tall.', 90]], [],
      [['proag', 4, '', 'Full speed. Stay low through the turns.', 60], ['h1b', 3, '', 'Dry swing, then sprint through the bag.', 90]], [] ],
    [ [['s10', 3, '10 yd', 'Full speed.', 60], ['s30', 4, '30 yd', 'Have a partner time you if you can.', 90]], [],
      [['h1b', 4, '', 'Sprint through the bag, do not slow down early.', 90], ['f3b', 3, '', 'Hard turn at second, full speed into third.', 120]], [] ],
    [ [['s30', 3, '30 yd', 'Full speed.', 90], ['s60', 2, '60 yd', 'Timed test. Have a partner time you.', 180]], [],
      [['h1b', 3, '', 'Timed test.', 90], ['proag', 3, '', 'Timed test.', 90]], [] ]
  ],

  // Arm care closes every session. Phases 1 and 2 use list A, phases 3 and 4 use list B.
  armCarePhase: [0, 0, 1, 1],
  armCare: [
    [ ['bander', 2, '15', 'Elbow pinned to your side. Slow on the way back.', 30],
      ['bandir', 2, '15', 'Elbow pinned to your side.', 30],
      ['pullapart', 2, '15', 'Squeeze your shoulder blades together at the end.', 30],
      ['ytw', 1, '8 ea', 'Thumbs up, no weight. 8 of each letter.', 30],
      ['wrist', 1, '15 ea', 'Light dumbbell. Curls, then extensions.', 30] ],
    [ ['er90', 2, '12', 'Elbow at shoulder height, bent 90 degrees. Slow and controlled.', 30],
      ['ir90', 2, '12', 'Elbow at shoulder height, bent 90 degrees.', 30],
      ['ytw', 2, '8 ea', 'Add a 1 to 2.5 lb plate only if form stays perfect.', 30],
      ['scappush', 2, '10', 'Arms stay straight. Pinch shoulder blades, then push them apart.', 30],
      ['wrist', 2, '15 ea', 'Light dumbbell.', 30] ]
  ],

  // Main work. tracks.beginner[phase][day] and tracks.experienced[phase][day]
  tracks: {
    beginner: [
      [ // Phase 1: Foundation
        [ ['goblet', 3, '12', 'Light dumbbell. Sit deep with a tall chest.', 90],
          ['dl', 3, '8', 'Empty bar or very light. Learn the hip hinge.', 120],
          ['lunge', 3, '10 ea', 'Bodyweight or light dumbbells.', 90],
          ['plank', 2, '30s', 'Straight line from head to heels.', 60],
          ['deadbug', 2, '12', 'Slow. Low back stays pressed to the floor.', 60] ],
        [ ['pushup', 3, '8-10', 'Hands on a bench if you need to. Perfect reps only.', 90],
          ['latpd', 3, '10', 'Pull the bar to your upper chest.', 90],
          ['lowinc', 2, '10', 'Bench set at 30 degrees. Light and controlled.', 90],
          ['dbrow', 2, '10 ea', 'Knee and hand on a bench for support.', 90],
          ['rope', 2, '30s', 'Steady pace.', 60] ],
        [ ['lmrot', 2, '10 ea', 'Light weight. Learn the movement.', 90],
          ['deadbug', 3, '12', 'Perfect form comes first.', 75],
          ['suitcase', 2, '30 ft', 'Each hand. Light dumbbell. Stand tall, do not lean.', 75],
          ['mbchop', 2, '10 ea', 'Light ball, controlled.', 90],
          ['pallof', 2, '8 ea', 'Do not let your torso twist.', 75] ],
        [ ['stepup', 2, '8 ea', 'Step onto a bench or box. This builds up to box jumps.', 120],
          ['hklmpress', 2, '6 ea', 'Angled press, not straight overhead. Light weight, learn the drive.', 120],
          ['revlunge', 2, '10 ea', 'Controlled.', 90],
          ['burpeemod', 2, '5', 'Step back instead of jumping back.', 120],
          ['rope', 2, '30s', 'Steady pace.', 60] ]
      ],
      [ // Phase 2: Strength
        [ ['goblet', 3, '12', 'Heavier than Phase 1.', 120],
          ['dl', 3, '6', 'Light to moderate weight.', 120],
          ['bss', 3, '8 ea', 'Light dumbbells.', 90],
          ['plank', 3, '40s', '10 seconds longer than Phase 1.', 75],
          ['suitcase', 2, '40 ft', 'Each hand. Light dumbbell.', 75] ],
        [ ['pushup', 3, '10', 'Full push-ups if you can.', 120],
          ['latpd', 3, '12', 'Add weight when every set feels smooth.', 120],
          ['lowinc', 3, '8', 'Heavier than Phase 1.', 90],
          ['dbrow', 3, '10 ea', 'Heavier than Phase 1.', 90],
          ['dbcurl', 2, '10', 'Light to moderate.', 75] ],
        [ ['lmrot', 3, '10 ea', 'Light weight.', 90],
          ['deadbug', 3, '12', 'Slow and controlled.', 75],
          ['suitcase', 2, '40 ft', 'Each hand. Slightly heavier.', 75],
          ['mbchop', 2, '12 ea', 'Controlled.', 90],
          ['pallof', 3, '8 ea', 'Slightly heavier band or cable.', 75] ],
        [ ['boxjump', 3, '5', 'Your first box jumps. Low box, land soft, step down.', 120],
          ['hklmpress', 3, '6 ea', 'Angled press. Slightly heavier.', 120],
          ['jumplunge', 2, '8 ea', 'Your first jumping lunges. Land soft.', 120],
          ['burpee', 2, '6', 'Full burpees now.', 120],
          ['ropes', 2, '30s', 'Hard, steady pace for all 30 seconds.', 90] ]
      ],
      [ // Phase 3: Power
        [ ['bsq', 3, '8', 'Your first barbell squats. Light, learn with a coach. Use the safety bars.', 120],
          ['jumpsq', 3, '6', 'Explode up, land soft.', 120],
          ['bss', 3, '8 ea', 'Heavier than Phase 2.', 90],
          ['abwheel', 2, '8', 'From your knees.', 90],
          ['wplank', 3, '45s', 'Light plate on your back only if your form stays perfect.', 90] ],
        [ ['pushup', 3, '12', 'Full push-ups.', 120],
          ['latpd', 3, '10', 'Heavier than Phase 2.', 120],
          ['floorpress', 3, '8', 'Press fast, lower slow.', 120],
          ['dbrow', 3, '10 ea', 'Heavier than Phase 2.', 90],
          ['plyopush', 2, '5', 'Your first explosive push-ups. Knees down is fine.', 120] ],
        [ ['lmrot', 3, '12 ea', 'Moderate weight, explosive.', 90],
          ['mbrotslam', 3, '8 ea', 'Rotate and slam to each side.', 120],
          ['mbchop', 2, '12 ea', 'Controlled and powerful.', 90],
          ['wdeadbug', 2, '10', 'Hold a light plate over your chest.', 90],
          ['suitcase', 3, '50 ft', 'Each hand. Heavier.', 75] ],
        [ ['boxjump', 4, '5', 'Slightly higher box. Full effort, soft landing.', 120],
          ['dbhighpull', 3, '6', 'Explode with your legs, pull your elbows high.', 120],
          ['jumplunge', 3, '6 ea', 'Land soft.', 90],
          ['kbswing', 3, '12', 'Heavier than Phase 2.', 120],
          ['sprintint', 4, '40 yd', 'Build to about 90 percent speed.', 90] ]
      ],
      [ // Phase 4: Peak
        [ ['bsq', 3, '6', 'Last set around RPE 7, about 3 reps left. Use the safety bars.', 120],
          ['expstepup', 3, '6 ea', 'Drive up fast.', 90],
          ['boxjump', 3, '5', 'Full effort, full rest.', 120],
          ['wplank', 3, '50s', 'Light plate.', 90],
          ['farmer', 3, '60 ft', 'Heavy dumbbells. Walk tall.', 75] ],
        [ ['bench', 3, '6', 'Your first barbell bench. Last set around RPE 7. Spotter required.', 120],
          ['pullup', 3, '5-6', 'Use a band or machine assist if needed.', 120],
          ['cgdb', 3, '8', 'Dumbbells pressed together. Triceps focus.', 90],
          ['bbrow', 3, '8', 'Moderate weight.', 120],
          ['plyopush', 2, '6', 'Explosive.', 120] ],
        [ ['lmrot', 3, '8 ea', 'Heavier, explosive.', 120],
          ['mbrot', 3, '8 ea', 'Throw hard into a wall.', 120],
          ['hlr', 3, '8', 'Strict. Bent knees are fine.', 90],
          ['abwheel', 3, '10', 'Full extension if you can control it.', 90],
          ['cablerot', 3, '10 ea', 'Rotate fast, control the return.', 75] ],
        [ ['boxjump', 4, '3', 'Full effort, soft landing.', 120],
          ['dbhighpull', 3, '6', 'Explosive.', 120],
          ['broad', 3, '5', 'Stick every landing. Walk back.', 120],
          ['kbswing', 3, '15', 'Heavy but controlled.', 120],
          ['sportdrill', 3, '', 'Throwing progression, agility, or reaction drills as assigned.', 90] ]
      ]
    ],
    experienced: [
      [ // Phase 1: Foundation
        [ ['bsq', 4, '8', 'Moderate weight. Perfect form.', 120],
          ['dl', 4, '6', 'Build up gradually across sets.', 120],
          ['bss', 3, '8 ea', 'Dumbbells.', 90],
          ['abwheel', 3, '6', 'Or a plank for 3 x 45 seconds.', 90],
          ['suitcase', 3, '50 ft', 'Each hand.', 75] ],
        [ ['bench', 4, '6', 'Build up across sets. Spotter required.', 120],
          ['bbrow', 4, '6', 'Similar effort to your bench.', 120],
          ['pullup', 3, '6-10', 'Use a band or machine assist if needed.', 90],
          ['incdb', 3, '8', 'Controlled tempo.', 90],
          ['plyopush', 2, '5', 'Hands leave the ground. Full rest.', 120] ],
        [ ['lmrot', 3, '12 ea', 'Moderate weight, explosive.', 90],
          ['woodchop', 3, '10 ea', 'Rotate fast, return slow.', 90],
          ['mbslam', 3, '8', 'Every rep at full power.', 120],
          ['abwheel', 3, '8', 'From your knees is fine.', 90],
          ['suitcase', 3, '50 ft', 'Each hand. Heavier than Monday.', 75] ],
        [ ['boxjump', 3, '5', 'Moderate height. Step down. Full recovery.', 120],
          ['lmpush', 3, '6', 'Angled press, not straight overhead. Dip and drive.', 120],
          ['sldl', 3, '6 ea', 'Dumbbells. Balance first.', 90],
          ['plyopush', 3, '5', 'Explosive, full rest.', 90],
          ['ropes', 3, '30s', 'Hard, steady pace for all 30 seconds.', 90] ]
      ],
      [ // Phase 2: Strength
        [ ['bsq', 4, '6', 'Heavier than Phase 1. The app tells you when to add weight.', 120],
          ['dl', 4, '5', 'Heavier than Phase 1.', 120],
          ['sldl', 3, '6 ea', 'Dumbbells or a light kettlebell.', 90],
          ['abwheel', 3, '8', 'Two more reps than Phase 1.', 90],
          ['suitcase', 3, '60 ft', 'Each hand. Longer carry.', 75] ],
        [ ['bench', 4, '5', 'Spotter required.', 120],
          ['bbrow', 4, '5', 'Heavier than Phase 1.', 120],
          ['pullup', 3, '5', 'Add 5 to 10 lb with a belt or dumbbell if you can do 8 clean reps.', 120],
          ['incdb', 3, '6', 'Heavier than Phase 1.', 90],
          ['bbcurl', 3, '6', 'Light to moderate.', 75] ],
        [ ['lmrot', 3, '12 ea', 'Heavier than Phase 1.', 120],
          ['woodchop', 3, '12 ea', 'Rotate fast, return slow.', 120],
          ['mbslam', 3, '10', 'Every rep at full power.', 120],
          ['hlr', 3, '6', 'Strict. No swinging.', 90],
          ['suitcase', 3, '60 ft', 'Each hand. Heavier.', 75] ],
        [ ['boxjump', 4, '5', 'Higher box than Phase 1. Full recovery.', 120],
          ['lmpush', 4, '5', 'Slightly heavier. Dip and drive.', 120],
          ['jumpsq', 3, '8', 'Land soft and rebound.', 120],
          ['plyopush', 3, '6', 'Explosive.', 120],
          ['kbswing', 3, '12', 'Snap your hips. Your arms just guide the bell.', 120] ]
      ],
      [ // Phase 3: Power
        [ ['fsq', 4, '4', 'Heavy: about 2 reps left on the last set.', 120],
          ['jumpsq', 4, '6', 'Maximum height every rep.', 120],
          ['sldl', 3, '6 ea', 'Heavier dumbbells.', 90],
          ['abwheel', 3, '10', 'Full extension if you can control it.', 90],
          ['wplank', 3, '60s', 'Plate on your back.', 90] ],
        [ ['bench', 4, '4', 'Heavy: about 2 reps left on the last set. Spotter required.', 120],
          ['pullup', 4, '4', 'Weighted if you can.', 120],
          ['floorpress', 3, '8', 'Press fast, lower slow.', 120],
          ['bbrow', 3, '5', 'Heavy: about 2 reps left on the last set.', 120],
          ['plyopush', 3, '8', 'Push off the ground as high as you can.', 120] ],
        [ ['lmrot', 3, '10 ea', 'Heavier and explosive.', 120],
          ['mbrotslam', 4, '8 ea', 'Full power every rep.', 120],
          ['lmpush', 4, '5', 'Angled press. Fast reps.', 120],
          ['wdeadbug', 3, '10', 'Moderate plate.', 90],
          ['suitcase', 3, '60 ft', 'Each hand. Heavy.', 75] ],
        [ ['boxjump', 5, '5', 'Highest box you can land cleanly. Full rest.', 120],
          ['clean', 4, '3', 'Technique first, coach present. Stop the set if form breaks.', 120],
          ['jumplunge', 3, '8 ea', 'Full power.', 120],
          ['kbswing', 3, '15', 'Heavy.', 120],
          ['sprintint', 5, '50 yd', 'Near full speed.', 90] ]
      ],
      [ // Phase 4: Peak
        [ ['bsq', 4, '3', 'Heavy: 1 to 2 reps left on the last set. Never grind a rep.', 120],
          ['expstepup', 3, '6 ea', 'Heavier dumbbells. Drive up fast.', 120],
          ['depthjump', 4, '5', 'Low box, 12 to 18 inches. Step off, land, jump right away.', 120],
          ['wplank', 3, '60s', 'Heavier plate.', 90],
          ['farmer', 3, '60 ft', 'Heaviest you can carry with tall posture.', 75] ],
        [ ['bench', 4, '3', 'Heavy: 1 to 2 reps left on the last set. Spotter required.', 120],
          ['pullup', 4, '4', 'Weighted.', 120],
          ['cgbench', 3, '5', 'Heavy: about 2 reps left on the last set.', 90],
          ['bbrow', 4, '3', 'Heavy: 1 to 2 reps left on the last set.', 120],
          ['plyopush', 3, '6', 'Explosive.', 120] ],
        [ ['lmrot', 3, '8 ea', 'Heavy and explosive.', 120],
          ['mbrot', 4, '8 ea', 'Full power every throw.', 120],
          ['hlr', 3, '8', 'Hold a light dumbbell between your feet only if strict reps are easy.', 120],
          ['abwheel', 3, '12', 'Full extension if you can control it.', 90],
          ['cablerot', 3, '10 ea', 'Heavier, fast rotation.', 75] ],
        [ ['boxjump', 5, '3', 'Highest box you can land cleanly.', 120],
          ['clean', 4, '2', 'Heavy but fast and crisp, about 2 reps left. Stop if the bar slows down.', 120],
          ['broad', 4, '5', 'Maximum distance. Stick the landing.', 120],
          ['kbswing', 3, '15', 'Heaviest bell you can snap with good form.', 120],
          ['sportdrill', 3, '', 'Throwing progressions and baseball movements.', 90] ]
      ]
    ]
  },

  /*
    EXERCISE LIBRARY
    id: [name, category, how it is logged, equipment, coaching cue, flags]
    category: lift, plyo, core, arm, cardio, sprint
    logged:   weight, bw (reps), hold (seconds), sprint, dist (jump distance), box, mb (med ball), carry, check, cardio, intervals
    equipment: bar, db (per hand), db1 (one dumbbell), kb, machine, bw
    flags: 'bwok' means bodyweight is allowed with no weight entered
  */
  exercises: {
    goblet: ['Goblet Squat', 'lift', 'weight', 'db1', 'Hold one dumbbell at your chest. Squat deep with elbows inside your knees, chest up, weight in your heels. Drive up through your heels.'],
    dl: ['Deadlift', 'lift', 'weight', 'bar', 'Bar over mid-foot, shins vertical, flat back. Push the floor away so hips and shoulders rise together. Stand tall at the top, then lower with control. Keep the bar close.'],
    bsq: ['Back Squat', 'lift', 'weight', 'bar', 'Bar across your upper back, feet shoulder-width, toes slightly out. Brace your core, sit to parallel, drive up through your heels. Always use safety bars or a spotter.'],
    fsq: ['Front Squat', 'lift', 'weight', 'bar', 'Bar resting on the front of your shoulders, elbows high. Squat to parallel keeping your chest up. More quad-focused than the back squat.'],
    lunge: ['Walking Lunge', 'lift', 'weight', 'db', 'Step forward, drop your back knee toward the floor, front knee over your ankle. Drive through your front foot into the next step.', 'bwok'],
    revlunge: ['Reverse Lunge', 'lift', 'weight', 'db', 'Step back and lower until both knees are about 90 degrees. Push through your front foot to return.', 'bwok'],
    bss: ['Bulgarian Split Squat', 'lift', 'weight', 'db', 'Rear foot on a bench. Front foot far enough forward that you can drop straight down. Lower until your front thigh is parallel, drive up through your front foot.', 'bwok'],
    stepup: ['Step-Up', 'lift', 'weight', 'db', 'Whole foot on the box. Drive through that leg to stand tall on top, then step down with control. Do not push off the back foot.', 'bwok'],
    expstepup: ['Explosive Step-Up', 'lift', 'weight', 'db', 'Same as a step-up, but drive up as fast as you can. Control the step down.', 'bwok'],
    sldl: ['Single-Leg Deadlift', 'lift', 'weight', 'db', 'Stand on one leg with a slight knee bend. Hinge at the hips as the free leg reaches back. Keep hips square, then stand tall.'],
    latpd: ['Lat Pulldown', 'lift', 'weight', 'machine', 'Hands slightly wider than shoulders. Pull the bar to your upper chest, squeeze your back, return slowly to full stretch.'],
    lowinc: ['Low-Incline DB Press', 'lift', 'weight', 'db', 'Bench at about 30 degrees. Press the dumbbells up and slightly together, lower with control to chest level. Angled, never straight overhead.'],
    incdb: ['Incline DB Press', 'lift', 'weight', 'db', 'Bench at 30 to 45 degrees. Press up, lower slowly to chest level. Keep your shoulder blades pulled back.'],
    dbrow: ['One-Arm DB Row', 'lift', 'weight', 'db', 'Knee and hand on a bench, flat back. Pull the dumbbell to your hip and squeeze your back. Lower with control.'],
    bench: ['Bench Press', 'lift', 'weight', 'bar', 'Feet flat, back on the bench, grip slightly wider than shoulders. Lower the bar to your chest with control, press up hard. Spotter required.'],
    bbrow: ['Barbell Row', 'lift', 'weight', 'bar', 'Hinge forward with a flat back. Pull the bar to your lower chest, squeeze your shoulder blades, lower with control.'],
    cgbench: ['Close-Grip Bench Press', 'lift', 'weight', 'bar', 'Hands about shoulder-width. Elbows stay close to your sides. Triceps focus. Spotter required.'],
    cgdb: ['Close-Grip DB Press', 'lift', 'weight', 'db', 'Press two dumbbells squeezed together over your chest. Elbows tucked. Triceps focus.'],
    floorpress: ['DB Floor Press', 'lift', 'weight', 'db', 'Lie on the floor. Lower until your upper arms touch the floor, pause, press up fast.'],
    dbcurl: ['DB Curl', 'lift', 'weight', 'db', 'Elbows pinned to your sides. Curl up, lower slowly. No swinging.'],
    bbcurl: ['Barbell Curl', 'lift', 'weight', 'bar', 'Elbows at your sides. Curl up, lower slowly. No swinging.'],
    hklmpress: ['Half-Kneeling Landmine Press', 'lift', 'weight', 'bar', 'Kneel on one knee holding the end of the landmine bar at your shoulder. Press up and forward at an angle, not straight overhead. Core tight, ribs down.'],
    lmpush: ['Landmine Push Press', 'plyo', 'weight', 'bar', 'Stand holding the end of the landmine bar at your shoulder. Quick dip with your legs, then drive the bar up and forward at an angle. Lower with control.'],
    clean: ['Power Clean', 'plyo', 'weight', 'bar', 'Start like a deadlift. Pull fast with your legs, shrug, and catch the bar on your shoulders in a quarter squat. Only with a coach present.'],
    dbhighpull: ['DB High Pull', 'plyo', 'weight', 'db', 'Start in a hinge. Explode up with your legs and pull the dumbbells up with elbows high and out.'],
    kbswing: ['Kettlebell Swing', 'plyo', 'weight', 'kb', 'Hinge at the hips, hike the bell back, then snap your hips forward so the bell floats to chest height. Your arms just guide it.'],
    pushup: ['Push-Up', 'lift', 'bw', 'bw', 'Hands slightly wider than shoulders, body in a straight line. Chest nearly to the floor, press all the way up. Hands on a bench makes it easier.'],
    plyopush: ['Plyometric Push-Up', 'plyo', 'bw', 'bw', 'Lower with control, then push so hard your hands leave the ground. Land softly and reset.'],
    pullup: ['Pull-Up', 'lift', 'bw', 'bw', 'Hands slightly wider than shoulders. Pull until your chin clears the bar, lower all the way down. Use a band or machine assist if needed. Enter added weight if you use a belt.'],
    jumpsq: ['Jump Squat', 'plyo', 'bw', 'bw', 'Squat to a comfortable depth, jump as high as you can reaching up, land softly back into the squat.'],
    jumplunge: ['Jumping Lunge', 'plyo', 'bw', 'bw', 'From a lunge, jump and switch legs in the air. Land soft in a lunge on the other side.'],
    depthjump: ['Depth Jump', 'plyo', 'bw', 'bw', 'Stand on a low box (12 to 18 in). Step off, do not jump off. Land and immediately jump as high as you can.'],
    boxjump: ['Box Jump', 'plyo', 'box', 'bw', 'Quick dip, jump, land softly on both feet on top of the box. Step down, never jump down. Rest fully between reps.'],
    broad: ['Broad Jump', 'plyo', 'dist', 'bw', 'Swing your arms back, then jump forward as far as you can. Stick the landing without falling forward. Measure to your heels.'],
    mbslam: ['Med Ball Slam', 'plyo', 'mb', 'bw', 'Ball overhead, then slam it into the ground as hard as you can. Retrieve and repeat.'],
    mbrotslam: ['Rotational Med Ball Slam', 'plyo', 'mb', 'bw', 'Ball overhead, rotate, and slam it down outside one foot. Alternate or finish one side first.'],
    mbrot: ['Med Ball Rotational Throw', 'plyo', 'mb', 'bw', 'Stand sideways to a wall. Load your back hip, then rotate and throw the ball into the wall as hard as you can.'],
    mbchop: ['Med Ball Chop', 'core', 'mb', 'bw', 'Start with the ball high over one shoulder, chop it down across your body to the opposite hip. Controlled and powerful.'],
    burpee: ['Burpee', 'cardio', 'bw', 'bw', 'Squat, hands down, jump back to a push-up, push-up, jump feet in, jump up.'],
    burpeemod: ['Step-Back Burpee', 'cardio', 'bw', 'bw', 'Squat, hands down, step back to a plank one foot at a time, step in, stand up.'],
    ropes: ['Battle Ropes', 'cardio', 'hold', 'bw', 'Athletic stance, core tight. Make fast, even waves for the full time.'],
    rope: ['Jump Rope', 'cardio', 'hold', 'bw', 'Turn the rope with your wrists, stay on the balls of your feet, land softly.'],
    plank: ['Plank', 'core', 'hold', 'bw', 'Elbows under shoulders, straight line from head to heels. Squeeze your glutes, do not let your hips sag.'],
    wplank: ['Weighted Plank', 'core', 'hold', 'bw', 'Plank with a plate on your upper back, placed by a partner. Only add weight if your form stays perfect.'],
    deadbug: ['Dead Bug', 'core', 'bw', 'bw', 'On your back, arms up, knees at 90 degrees. Lower opposite arm and leg, keep your low back pressed to the floor. Alternate.'],
    wdeadbug: ['Weighted Dead Bug', 'core', 'bw', 'bw', 'Dead bug holding a light plate over your chest. Enter the plate weight if you use one.'],
    suitcase: ['Suitcase Carry', 'core', 'carry', 'db', 'Heavy dumbbell in one hand. Walk tall with level shoulders, do not lean. Switch hands.'],
    farmer: ['Farmer Carry', 'core', 'carry', 'db', 'Heavy dumbbell in each hand. Walk tall, shoulders back, short quick steps.'],
    pallof: ['Pallof Press', 'core', 'bw', 'bw', 'Stand sideways to a cable or band. Press your hands straight out from your chest and hold, resisting the twist. Return and repeat.'],
    lmrot: ['Landmine Rotation', 'core', 'weight', 'bar', 'Hold the end of the landmine bar at shoulder height with both hands. Rotate from hip to hip, pivoting your back foot. Control the bar.'],
    woodchop: ['Cable Woodchop', 'core', 'weight', 'machine', 'Pull the cable from high to low across your body, rotating through your hips. Return slowly.'],
    cablerot: ['Cable Rotation', 'core', 'weight', 'machine', 'Cable at chest height. Arms straight, rotate away fast, return slowly.'],
    abwheel: ['Ab Wheel Rollout', 'core', 'bw', 'bw', 'From your knees, roll out as far as you can keep a flat back, then pull back in with your abs.'],
    hlr: ['Hanging Leg Raise', 'core', 'bw', 'bw', 'Hang from a bar. Raise your legs (bent or straight) without swinging. Lower slowly. Enter added weight if you use a dumbbell.'],
    s10: ['10-Yard Sprint', 'sprint', 'sprint', 'bw', 'Two-point start, lean forward, drive your arms. Time is optional; enter it if a partner times you.'],
    s30: ['30-Yard Sprint', 'sprint', 'sprint', 'bw', 'Stay low for the first 10 yards, then run tall. Time is optional.'],
    s60: ['60-Yard Dash', 'sprint', 'sprint', 'bw', 'Full-speed 60. Time it with a partner if you can.'],
    h1b: ['Home to First', 'sprint', 'sprint', 'bw', 'From your batting stance, dry swing and sprint through the bag. Do not slow down before the base.'],
    f3b: ['First to Third', 'sprint', 'sprint', 'bw', 'Lead off first, take a hard turn at second, and sprint into third.'],
    proag: ['Pro Agility (5-10-5)', 'sprint', 'sprint', 'bw', 'Start straddling a line. Sprint 5 yards and touch, sprint 10 yards back and touch, sprint 5 through the start.'],
    sprintint: ['Sprint Repeats', 'sprint', 'sprint', 'bw', 'Sprint the listed distance, walk back to recover. Time is optional.'],
    sportdrill: ['Sport-Specific Drills', 'cardio', 'check', 'bw', 'Throwing progression, agility, or reaction drills as your coach assigns. Check off each round.'],
    bander: ['Band External Rotation', 'arm', 'bw', 'bw', 'Elbow pinned to your side, bent 90 degrees. Rotate your hand out against the band, return slowly.'],
    bandir: ['Band Internal Rotation', 'arm', 'bw', 'bw', 'Elbow pinned to your side, bent 90 degrees. Rotate your hand in across your body, return slowly.'],
    er90: ['Band External Rotation at 90', 'arm', 'bw', 'bw', 'Elbow at shoulder height, bent 90 degrees. Rotate your hand up and back against the band, return slowly.'],
    ir90: ['Band Internal Rotation at 90', 'arm', 'bw', 'bw', 'Elbow at shoulder height, bent 90 degrees. Rotate your hand forward and down, return slowly.'],
    pullapart: ['Band Pull-Apart', 'arm', 'bw', 'bw', 'Arms straight in front, pull the band apart to your chest. Squeeze your shoulder blades.'],
    ytw: ['Y-T-W Raises', 'arm', 'bw', 'bw', 'Face down on a bench or bent over. Raise your arms into a Y, then a T, then a W. Thumbs up. Enter plate weight if used.'],
    scappush: ['Scap Push-Up', 'arm', 'bw', 'bw', 'In a push-up position with straight arms, let your shoulder blades pinch together, then push them apart.'],
    wrist: ['Wrist Curls and Extensions', 'arm', 'bw', 'bw', 'Forearm on your thigh with a light dumbbell. Curl the wrist up, then flip over and extend. Enter dumbbell weight if you like.'],
    // Extra exercises for logging extra work
    rdl: ['Romanian Deadlift', 'lift', 'weight', 'bar', 'Soft knees, push your hips back until you feel your hamstrings, keep the bar close, stand tall.'],
    tbdl: ['Trap Bar Deadlift', 'lift', 'weight', 'bar', 'Stand inside the bar, flat back, push the floor away.'],
    hipthrust: ['Barbell Hip Thrust', 'lift', 'weight', 'bar', 'Upper back on a bench, bar over your hips. Drive your hips up and squeeze.'],
    dbbench: ['DB Bench Press', 'lift', 'weight', 'db', 'Press the dumbbells up over your chest, lower with control.'],
    landmine: ['Landmine Press', 'lift', 'weight', 'bar', 'Press the end of the landmine bar up and forward at an angle.'],
    chinup: ['Chin-Up', 'lift', 'bw', 'bw', 'Palms facing you. Pull your chin over the bar, lower all the way.'],
    invrow: ['Inverted Row', 'lift', 'bw', 'bw', 'Hang under a bar with a straight body. Pull your chest to the bar.'],
    nordic: ['Nordic Hamstring Curl', 'lift', 'bw', 'bw', 'Kneel with ankles held. Lower forward as slowly as you can.'],
    vert: ['Vertical Jump', 'plyo', 'dist', 'bw', 'Jump straight up as high as you can. Enter inches.'],
    latbound: ['Lateral Bound', 'plyo', 'bw', 'bw', 'Bound sideways off one leg, stick the landing on the other.'],
    skater: ['Skater Jump', 'plyo', 'bw', 'bw', 'Leap side to side like a speed skater.'],
    pogo: ['Pogo Hops', 'plyo', 'bw', 'bw', 'Quick, stiff-ankle hops.'],
    mbscoop: ['Med Ball Scoop Toss', 'plyo', 'mb', 'bw', 'Scoop the ball from low and throw it into a wall with your hips.'],
    mbchest: ['Med Ball Chest Pass', 'plyo', 'mb', 'bw', 'Explosive chest pass into a wall.'],
    splank: ['Side Plank', 'core', 'hold', 'bw', 'Elbow under shoulder, straight line, hips up.'],
    copen: ['Copenhagen Plank', 'core', 'hold', 'bw', 'Side plank with your top leg on a bench.'],
    birddog: ['Bird Dog', 'core', 'bw', 'bw', 'On hands and knees, extend opposite arm and leg.'],
    hkr: ['Hanging Knee Raise', 'core', 'bw', 'bw', 'Hang and bring your knees up without swinging.'],
    facepull: ['Face Pull', 'arm', 'bw', 'bw', 'Pull the rope toward your face, elbows high.'],
    sleeper: ['Sleeper Stretch', 'arm', 'hold', 'bw', 'Gentle stretch only, no pain.'],
    run: ['Run', 'cardio', 'cardio', 'bw', 'Log minutes and distance.'],
    bike: ['Bike', 'cardio', 'cardio', 'bw', 'Log minutes and distance.'],
    rower: ['Rower', 'cardio', 'cardio', 'bw', 'Log minutes and distance.'],
    tempo: ['Tempo Runs', 'cardio', 'intervals', 'bw', 'Log reps, distance, and time per rep.'],
    sint: ['Sprint Intervals', 'sprint', 'intervals', 'bw', 'Log reps, distance, and time per rep.']
  }
};
